import type { Metadata } from "next";
import "./globals.scss";

import Header from "./components/layout/Header"
import Footer from "./components/layout/Footer"
import Breadcrumb from "./components/layout/Breadcrumb";
import Script from "next/script";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <title>Meu Site</title>
        <meta name="description" content="Descrição do meu site" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.cdnfonts.com/css/rawline" />
        <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' />
      </head>
      <body>
        <Script src="/core.min.js" strategy="beforeInteractive"></Script>
        <Script src="/core-init.min.js" strategy="beforeInteractive"></Script>
        <Header></Header>
        <main className="container my-4">
          <Breadcrumb></Breadcrumb>
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
